-- =====================================================
-- Skema Database Smart Tabungan (PostgreSQL untuk Supabase)
-- Target: Supabase (PostgreSQL 15+)
-- =====================================================

-- 1. Kartu RFID yang boleh membuka kunci (Solenoid)
CREATE TABLE rfid_cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid TEXT NOT NULL UNIQUE,       -- contoh: 'BA8C6A06'
  owner_name TEXT,                -- Tambahan: Nama pemilik kartu (opsional)
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Transaksi (Setoran dari ESP32 & Pengeluaran dari Web)
-- Menggantikan tabel deposits lama agar bisa mendukung "pengeluaran"
CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_txn_id TEXT UNIQUE, -- ID unik dari ESP32 (NULL jika pengeluaran dari web)
  type TEXT NOT NULL CHECK (type IN ('deposit', 'expense')), -- deposit = masuk, expense = keluar
  amount BIGINT NOT NULL,    -- nominal transaksi (rupiah)
  description TEXT,          -- keterangan (misal: "Beli Laptop" atau "Setoran Celengan")
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_transactions_time ON transactions(created_at);

-- 3. Log setiap tap kartu untuk buka kunci pintu
-- 'unknown' = UID tidak ada di rfid_cards (diisi oleh server, bukan ESP32)
CREATE TABLE rfid_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_uid TEXT NOT NULL,
  event TEXT NOT NULL CHECK (event IN ('known', 'unknown')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_rfid_events_card_time ON rfid_events(card_uid, created_at);
CREATE INDEX idx_rfid_events_time ON rfid_events(created_at);

-- 4. Aktivitas mencurigakan (diisi oleh web/AI ketika mendeteksi 5x unknown tap beruntun)
-- emailed_at diisi saat alert Gmail terkirim, supaya tidak kirim email dobel
CREATE TABLE suspicious_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_uid TEXT,
  type TEXT NOT NULL,              -- contoh: 'UNKNOWN_CARD_SPAM'
  attempts SMALLINT NOT NULL DEFAULT 1,
  detail TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  emailed_at TIMESTAMPTZ
);
CREATE INDEX idx_suspicious_card_time ON suspicious_activities(card_uid, created_at);
CREATE INDEX idx_suspicious_unsent ON suspicious_activities(emailed_at, created_at);

-- 5. Data Awal (Contoh/Dummy) untuk dicoba
INSERT INTO transactions (type, amount, description) VALUES ('deposit', 50000, 'Setoran Awal via ESP32');

-- 6. Target Tabungan (Hanya butuh 1 baris untuk menyimpan target saat ini)
CREATE TABLE savings_target (
  id INT PRIMARY KEY DEFAULT 1,
  amount BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Sisipkan nilai target awal Rp 12.000.000
INSERT INTO savings_target (id, amount) VALUES (1, 12000000) ON CONFLICT (id) DO NOTHING;

-- 7. MATIKAN RLS AGAR APLIKASI BISA MENGAKSES DATABASE DENGAN ANON KEY (KHUSUS DEVELOPMENT)
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE savings_target DISABLE ROW LEVEL SECURITY;
ALTER TABLE rfid_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE suspicious_activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE rfid_cards DISABLE ROW LEVEL SECURITY;
